### ISSUE TITLE
Upload of IRs fails

### ISSUE THREAD

**Issue by sekret1** [TieDyedDevil/afx2tool-linux#2]
Hi! Now I'll switch to reporting bugs here ;)

I just tried to upload a user cab to the Axe to see if and how this works. But here's what I got

$ afx2-tool -u 65\ VOX\ 212\ 58-609\ 2.syx
PORT hw:2,0,0 CHANNEL 1 MODEL AXE-FX II
od: 65: No such file or directory
/usr/bin/afx2-tool: line 221: [: =: unary operator expected
afx2-tool: not an Axe-FX file

That user cab was made with an XL, I have a Mark 1, so the error COULD be caused by this. So I tried another IR, which I actually created with my own Axe. Here's the output:

$ afx2-tool -u Mesa\ CabClone\ -\ Closed\ Back.syx
PORT hw:2,0,0 CHANNEL 1 MODEL AXE-FX II
od: Mesa: No such file or directory
/usr/bin/afx2-tool: line 221: [: =: unary operator expected
afx2-tool: not an Axe-FX file

Ok, same issue...

Or is your tool just not made for IRs?

**Comment by TieDyedDevil** [comment]
Triggered by filename containing spaces. Should be resolved by 0.9.5.

Note that the tool should reject a syx file that was dumped from a different model of Axe-FX. (Mk i and Mk II are treated as the same model. However, FX is different than FX+) Your first test case should report "file not compatible with model", since you're trying to load an XL file into a Mk1.

To answer your closing question: all syx files are treated the same.

**Comment by TieDyedDevil** [comment]
I'm going to assume that this was resolved by 0.9.5. Please reopen if not.
